version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_USER: ${POSTGRESQL_VALIDATOR_USER_NAME}
      POSTGRES_PASSWORD: ${VALI_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local